### ISSUE TITLE
Issue using lex function on connect

### ISSUE THREAD

**Issue by BrownC36** [aws-samples/amazon-lex-customerservice-workshop#3]
Are there any configurations needed to be made to the IAM policy for the Lex bot? When I test the call and try to use the intent, it disconnects.

**Comment by angelarw** [comment]
Hi, 
No need to change the IAM policy for the bot. which step are you on when the error happens and can you share a screenshot or the error message?

**Comment by BrownC36** [comment]
It was the IAM policy. I was missing the right to post messages to Lex from Connect when making the call. Thank you!
