### ISSUE TITLE
Can I get User Input Voice (Audio file) from lex inside Lambda function to recognise speaker talking to Lex bot

### ISSUE THREAD

**Issue by GauravGaikwad94** [aws-samples/amazon-lex-customerservice-workshop#4]
I want to recognise speaker talking to Lex bot, does AWS provide any service to recognise speaker?
Or if I want to use custom package to recognise speaker can I get user voice ( audio file ) inside Lambda function from Lex bot?

**Comment by corserv** [comment]
I've been looking into this and it so far looks not possible. But it may be. About a year ago Time ran an article saying Amazon was working on it [0]

Last Oct Alexa supposedly gained the ability to distinguish voices [1]. However, I can't find any api's to hook into it. 


[0] http://time.com/4683981/amazon-echo-voice-id-feature-2017/  (has autoplay video)
[1] https://www.theverge.com/circuitbreaker/2017/10/11/16460120/amazon-echo-multi-user-voice-new-feature

**Comment by angelarw** [comment]
Lex itself doesn't provide you the audio file, however, if you are using Lex with Amazon Connect, Amazon Connect does have call recording functionality: https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-instance.html
