### ISSUE TITLE
Mic/audio playback does not work in FF 59.0.1

### ISSUE THREAD

**Issue by corserv** [aws-samples/amazon-lex-customerservice-workshop#5]
Mic/audio playback does not work on FF 59.0.1 or nightly build 60.0b5.
Works fine in up-to-date IE Edge and Chrome.

We tested on three separate computers. All had the same results with FF not working and Chrome/IE working correctly.

FF Console is reporting.

Media resource blob:https://lex-web-ui-codebuilddeploy-1pxeax9qz-webappbucket-.....s3.amazonaws.com/9e9845e4-bb96-404e-b4f4-6692de6a2e70 could not be decoded.
index.html

All candidate resources failed to load. Media load paused.
index.html

Media resource blob:https://lex-web-ui-codebuilddeploy-1pxeax9qz-webappbucket-....s3.amazonaws.com/9e9845e4-bb96-404e-b4f4-6692de6a2e70 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006)

Edited URL to remove the actual bucket

**Comment by angelarw** [comment]
Thanks for reporting the issue! This is a feedback to the Lex product team. I have reached out to the Lex team and will report back when i hear back

**Comment by angelarw** [comment]
I have shared the feedback to the Lex team and they informed me it's on their backlog to fix. the current workaround is to use Chrome.
