### ISSUE TITLE
getting an "Invalid Lambda Response: Received error response from Lambda: Handled" in section 2C

### ISSUE THREAD

**Issue by tonyng42** [aws-samples/amazon-lex-customerservice-workshop#9]
I am stuck in section 2C. When I enter the test pin of "1234", I get the following in my test bot:
"An error has occurred: Invalid Lambda Response: Received error response from Lambda: Handled". I think this might be an issue with the lambda function code itself, but not sure how to troubleshoot / fix it. Thx!

**Comment by angelarw** [comment]
Hi [tonyng42](/tonyng42),

To troubleshoot, I suggest you take a look at the lambda logs (instructions to find logs is in module 1F). Feel free to share screenshots on the error you see if you'd like some help

**Comment by angelarw** [comment]
haven't heard back for 1.5 years.
